##
#
# 感谢p3terx大神的一键编译脚本
# 
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
#修改以下代码或者开启触发开关都好，要严格按格式对好,前面有多少空格也要看清楚
#代码里有 name: 后面的内容随便改,冒号后面是有个空格的,如果修改固件名字就要考虑能不能显示出你想要的

name: EVO 编译

#permissions: write-all
#开启写权限，防止无法上传到release

on: 
  workflow_dispatch:
#  schedule:
#    - cron: 0 16 * * *

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6
  REPO_BRANCH: openwrt-24.10-6.6
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  provision:
    runs-on: ubuntu-latest
    outputs:
      runner_label: ${{ steps.evo.outputs.runner_label }}
      instance_id: ${{ steps.evo.outputs.instance_id }}
    steps:
      - id: evo
        uses: Mythologyli/setup-evo-runner@main
        with:
          evo_api_token: ${{ secrets.EVO_API_TOKEN }}
          github_token: ${{ secrets.GH_PAT }}
          product_id: 41

  build:
    name: 编译mt7986-ax4200-bpir3_mini-mtwifi-cfg固件
    needs: provision
    runs-on: [self-hosted, "${{ needs.provision.outputs.runner_label }}"]

    steps:
    - name: 准备
      uses: actions/checkout@v3.1.0  
      
    - name: 检查磁盘空间
      run: |
           echo "Free space:"
           df -h

    - name: 开始安装编译所需系统
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential gawk gcc-multilib flex git gettext libncurses5-dev libssl-dev python3-distutils zlib1g-dev file
        sudo -E apt-get -y autoremove
        sudo -E apt-get autoclean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 下载固件源码
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH --depth=1 openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        
    - name: 更新 & 安装 feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 加载.config设置
      run: |
        cd openwrt
        cp -f defconfig/mt7986-ax4200-bpir3_mini.config .config
        echo CONFIG_PACKAGE_kmod-wireguard=y >> .config
        echo CONFIG_PACKAGE_kmod-nft-socket=y >> .config
        echo CONFIG_PACKAGE_kmod-nft-tproxy=y >> .config
        echo CONFIG_PACKAGE_kmod-netlink-diag=y >> .config
        
    - name: 下载软件包
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8 V=11
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译固件
      id: compile
      run: |
        cd openwrt
        echo -e "$(($(nproc)+1)) thread compile"
        make -j$(($(nproc)+1)) || make -j$(nproc) || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 整理文件
      id: organize
      if: steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf *.buildinfo
        rm -rf *.json
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: 上传固件目录
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: mt7986-ax4200-bpir3_mini-mtwifi-cfg
        path: ${{ env.FIRMWARE }}

    - name: 生成release标签
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")-ax3000-mtwifi-cfg">> $GITHUB_OUTPUT
        touch release.txt
        echo -e "immortalwrt-mt7986-ax4200-bpir3_mini-mtwifi-cfg 源码版本" >> release.txt
        echo "📥 固件下载" >> release.txt
        echo "status=success" >>$GITHUB_OUTPUT

    - name: 上传固件到release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: 删除旧发布的固件
      uses: dev-drprasad/delete-older-releases@v0.2.1
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 7
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
      needs: [provision, build]
      if: always()
      runs-on: ubuntu-latest
      steps:
        - uses: Mythologyli/setup-evo-runner/teardown@main
          with:
            evo_api_token: ${{ secrets.EVO_API_TOKEN }}
            instance_id: ${{ needs.provision.outputs.instance_id }}
